#pragma once

#define TOY_ARANHA "ARANHA"
#define TOY_SAPO "SAPO"
#define TOY_DENTADURA "DENTADURA"
#define TOY_FANTASIMNHA "FANTASMINHA"
#define TOY_BRUXINHA "BRUXINHA"


enum Toy
{
	ARANHA = 1,
	SAPO,
	DENTADURA,
	FANTASMINHA,
	BRUXINHA
};
